{% set name = "lcms2" %}
{% set version = "2.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mm2/Little-CMS/releases/download/lcms{{ version }}/lcms2-{{ version }}.tar.gz
  sha256: d473e796e7b27c5af01bd6d1552d42b45b43457e7182ce9903f38bb748203b88

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("lcms2") }}

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - make  # [not win]
  host:
    - jpeg
    - libtiff

test:
  commands:
    - test -f ${PREFIX}/include/lcms2.h  # [not win]
    - test ! -f ${PREFIX}/lib/liblcms2.a  # [not win]
    - test -f ${PREFIX}/lib/liblcms2${SHLIB_EXT}  # [not win]
    - jpgicc
    - tificc
    - linkicc
    - transicc
    - psicc
    - if not exist %LIBRARY_INC%\\lcms2.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\lcms2.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\lcms2.dll exit 1  # [win]

about:
  home: http://www.littlecms.com/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Open Source Color Management Engine

extra:
  recipe-maintainers:
    - isuruf
    - hmaarrfk
