travis:
  secure:
    BINSTAR_TOKEN: ZctzNYKQMZHMx44CVXRlYapCfWNxo7Pu2m4MhgoICOZoaSu1ogcxRahVnjkJVaMIVWw5rx/r/otKG86W92eeKEsdfh8JYw3dueqAbsxf8+sRRB6z7IhqyFMDeZm70JwdRyVad7znKEsXccyb+8U294Kx7tu0oSUB+kmYJmxfYnFzYgmmfVPkmQ6TG5oi8kZ+1xwNdn9LTV11Qh9KRpv7anNU9E4ug7fwcMjH3nzGHgUIcg9QP+AyCGFPE1fhbef2nQiEkaw3LwfDC4K/Zj2RTI57cuctgXn0NO3ujn6jdgI00uex1gs9QI/OhMzB7G9G02jyF1baX7lmiQP/7mK7vJFGRWtp8E+EaKNZGMg6otu1sM2kaClb1DcQ5REUv21mo2iZlD9n6ENhoJQmI/2Dl293o5tL2vSO2+IXVxkqUjRSU9n/YWaba/oapo1dES8mDiWi6PImZjV5Jlzd7yeF5awXK/4/yTFvtJRxdqscT+cFlP6DRA7JoQtsXfh0HY0E59RjxkCmHrYWgqrZve8DDv4FL1Uq7MQb2bI7tiMWqqNzAO2J93FKI5VMl1ocmgs47sTMCb4cXcMJ1t9hdM43HHVn7VLD5Z7l8PSluOW3m1s0UeM8Oc/q4Hz9dAInCqqEa5Rql3WVfT4Pqsg2viZTA10dK/K/0MTV4APGT9mbqY8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
